version: 2
updates:
  - package-ecosystem: "maven"
    directory: "retail-store-sample-app/src/cart"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "maven"
    directory: "retail-store-sample-app/src/orders"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "maven"
    directory: "retail-store-sample-app/src/ui"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "npm"
    directory: "retail-store-sample-app/src/checkout"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "retail-store-sample-app/src/catalog"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "npm"
    directory: "retail-store-sample-app/src/e2e"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "npm"
    directory: "retail-store-sample-app/src/load-generator"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
