apiVersion: v1
kind: PersistentVolume
metadata:
  name: opensearch-cluster-master-pv-master
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: opensearch-cluster-master-opensearch-cluster-master-0
    namespace: opensearch
  hostPath:
    path: /tmp/mypvsc
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  volumeMode: Filesystem