apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "bird"
    value: "goose"
    operator: "Exists"
    effect: "NoSchedule"