name: Checkout CI

on:
  push:
    branches:
    - main
    paths:
    - 'retail-store-sample-app/src/checkout/**'
  pull_request:
    branches:
    - main
    paths:
    - 'retail-store-sample-app/src/checkout/**'
    - 'retail-store-sample-app/images/**'
  workflow_dispatch:

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Run CI script
      run: |
        bash src/checkout/retail-store-sample-app/scripts/ci.sh

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v2
      with:
        image: tonistiigi/binfmt:latest
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Expose GitHub Runtime
      uses: crazy-max/ghaction-github-runtime@v2
        
    - name: Build container image
      run: |
        retail-store-sample-app/scripts/build-image.sh -s checkout -t ci --actions-cache